"""eqc — the equation compiler. ONE source-of-truth math expression → Rust code.

WHY THIS EXISTS (the "translation gap", closed).
The most error-prone moment in a math-first kernel is the hand-translation of a
formula into code: operator precedence, a dropped term, a wrong sign, a float
where an integer belongs. `eqc` removes the hand step: you write the equation
once (as a SymPy expression — the machine-checkable source of truth), and eqc
EMITS the Rust. What ships is ordinary, hand-inspectable Rust that is committed
to the repo and compiled normally.

NOT a runtime transpiler / proxy / middleware (cf. bebop2/ARCHITECTURE.md's
standing directive against those). eqc runs at AUTHORING time, offline. Its
output has ZERO runtime indirection — the generated `fn` is exactly what a
careful human would write, minus the transcription bugs. The equation is the
source; the Rust is a derived artifact, like an object file from source.

THE ONE FEATURE THAT MATTERS: dual emission from a single equation —
  1. `emit_f64_rust`   — the float variant (dynamics; SymPy's own Rust printer).
  2. `emit_fixed_rust` — the fixed-point (integer-scaled, Q-format) variant:
     bitwise-identical on every CPU/wasm target, the "crystalline" money-grade
     path. Refuses (honestly) on transcendentals it cannot represent exactly.
  3. `emit_proof_program` — a self-contained Rust program whose `main` ASSERTS
     f64 ≈ fixed ≈ the SymPy-evaluated reference at sample points. If codegen is
     wrong the asserts fail and `rustc && run` exits non-zero. The proof is the
     artifact, per the Mandatory Proof Rule.

Fixed-point model (Q-format): a real value v is carried as the integer
I = round(v · 2^SHIFT). Add: I₁+I₂. Mul: (I₁·I₂)/2^SHIFT (i128 intermediate,
truncating toward zero — deterministic). Pow(·,n≥0): repeated Mul. Const c:
round(c·2^SHIFT). This subset (±, ·, integer powers, constants) covers exactly
the money-law / polynomial organs that WANT determinism; sqrt/sin/exp are
dynamics and stay f64.

Dependency: sympy (`pip install sympy`), already resident in bebop-repo/.venv.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import sympy as sp
from sympy import rust_code


class FixedPointUnsupported(Exception):
    """Raised when an expression cannot be represented in the integer Q-format
    subset (e.g. sqrt/sin/exp, division by a symbol, negative/fractional power).
    Honest boundary: the caller falls back to the f64 variant for that organ."""


def _flit(x: float) -> str:
    """A valid Rust f64 literal: no e-notation, always a decimal point, `f64` suffix
    (avoids Python's `1e-07` and bare-int reprs which rustc rejects)."""
    s = repr(float(x))
    if "e" in s or "E" in s:
        s = f"{x:.17f}".rstrip("0")
        if s.endswith("."):
            s += "0"
    if "." not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f64"


@dataclass
class Equation:
    """A named equation: y = f(args...). `expr` is a SymPy expression over
    symbols whose names appear in `args` (order fixed → Rust parameter order)."""

    name: str
    args: Sequence[str]
    expr: sp.Expr
    scale_bits: int = 32  # Q32 fixed-point by default

    _symbols: dict = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        self._symbols = {a: sp.Symbol(a, real=True) for a in self.args}
        free = {s.name for s in self.expr.free_symbols}
        missing = free - set(self.args)
        if missing:
            raise ValueError(
                f"expr uses symbols not in args: {sorted(missing)} (args={list(self.args)})"
            )

    # ── float emission (reuse SymPy's proven Rust printer) ──────────────────
    def emit_f64_rust(self) -> str:
        body = rust_code(self.expr)
        params = ", ".join(f"{a}: f64" for a in self.args)
        return (
            f"/// GENERATED by eqc from: {self.name} = {self.expr}\n"
            f"/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).\n"
            f"#[inline(always)]\n"
            f"pub fn {self.name}_f64({params}) -> f64 {{\n"
            f"    {body}\n"
            f"}}"
        )

    # ── fixed-point emission (custom Q-format printer over the expr tree) ────
    def emit_fixed_rust(self) -> str:
        scale = self.scale_bits
        s_int = 1 << scale
        inner = self._emit_fixed(sp.sympify(self.expr), s_int)
        params = ", ".join(f"{a}: i64" for a in self.args)
        return (
            f"/// GENERATED by eqc from: {self.name} = {self.expr}\n"
            f"/// Fixed-point Q{scale} variant — inputs/output are round(v * 2^{scale}) as i64.\n"
            f"/// BITWISE-DETERMINISTIC on every target (pure integer arithmetic, i128 intermediates).\n"
            f"#[inline(always)]\n"
            f"pub fn {self.name}_fixed({params}) -> i64 {{\n"
            f"    const SHIFT: u32 = {scale};\n"
            f"    let _ = SHIFT; // documents the Q-format scale of inputs/output\n"
            f"    ({inner}) as i64\n"
            f"}}"
        )

    def _emit_fixed(self, expr: sp.Expr, s_int: int) -> str:
        """Recursively emit an i128-typed Rust expression at scale s_int (= 2^SHIFT)."""
        if expr.is_Symbol:
            return f"({expr.name} as i128)"
        if expr.is_Number:
            # constant c → round(c * S) as an i128 literal at scale S
            val = float(expr)
            return f"({round(val * s_int)}i128)"
        if expr.is_Add:
            return "(" + " + ".join(self._emit_fixed(a, s_int) for a in expr.args) + ")"
        if expr.is_Mul:
            parts = [self._emit_fixed(a, s_int) for a in expr.args]
            acc = parts[0]
            for p in parts[1:]:
                # each factor carries scale S; product carries S² → divide back to S
                acc = f"(({acc} * {p}) / {s_int}i128)"
            return acc
        if expr.is_Pow:
            base, exp = expr.args
            if not exp.is_Integer or int(exp) < 0:
                raise FixedPointUnsupported(
                    f"non-integer/negative exponent not fixed-point-representable: {expr}"
                )
            n = int(exp)
            if n == 0:
                return f"({s_int}i128)"  # 1.0 at scale S
            base_s = self._emit_fixed(base, s_int)
            acc = base_s
            for _ in range(n - 1):
                acc = f"(({acc} * {base_s}) / {s_int}i128)"
            return acc
        raise FixedPointUnsupported(
            f"node {type(expr).__name__} not in the fixed-point subset: {expr}"
        )

    # ── proof program (self-asserting Rust; exit 0 ⟺ codegen correct) ───────
    def emit_proof_program(self, samples: Sequence[dict], eps: float = 1e-6) -> str:
        """A standalone Rust program. For each sample it asserts:
        |f64_variant − reference| < eps  AND (if representable)
        |fixed_variant/2^SHIFT − reference| < eps, where `reference` is computed
        HERE by SymPy. Compile + run; a non-zero exit means codegen is wrong."""
        scale = self.scale_bits
        s_int = 1 << scale
        fns = self.emit_f64_rust()
        try:
            fns += "\n\n" + self.emit_fixed_rust()
            has_fixed = True
        except FixedPointUnsupported:
            has_fixed = False

        checks = []
        for i, smp in enumerate(samples):
            ref = float(self.expr.evalf(subs={self._symbols[a]: smp[a] for a in self.args}))
            f64_args = ", ".join(_flit(smp[a]) for a in self.args)
            checks.append(
                f'    let got = {self.name}_f64({f64_args});\n'
                f'    assert!((got - ({_flit(ref)})).abs() < {_flit(eps)}, '
                f'"f64 sample {i}: got {{}} want {ref}", got);'
            )
            if has_fixed:
                fixed_args = ", ".join(f"({round(smp[a] * s_int)}i64)" for a in self.args)
                checks.append(
                    f'    let got_fx = {self.name}_fixed({fixed_args}) as f64 / ({s_int}u64 as f64);\n'
                    f'    assert!((got_fx - ({_flit(ref)})).abs() < {_flit(eps)}, '
                    f'"fixed sample {i}: got {{}} want {ref}", got_fx);'
                )
        checks_src = "\n".join(checks)
        return (
            f"// GENERATED by eqc — self-asserting proof for `{self.name}`.\n"
            f"// exit 0 ⟺ the emitted f64 (and fixed-point) code matches the SymPy reference.\n"
            f"{fns}\n\n"
            f"fn main() {{\n"
            f"{checks_src}\n"
            f'    println!("eqc proof OK: {self.name} ({len(samples)} samples, '
            f'fixed={has_fixed})");\n'
            f"}}\n"
        )
