export const QUEUE_NAMES = {
  NOTIFY_DISPATCH: 'notify.dispatch',
  NOTIFY_CUSTOMER_STATUS: 'notify.customer_status',
  NOTIFY_TELEGRAM_SEND: 'notify.telegram.send',
  ORDER_PENDING_AGING: 'order.pending_aging',
  ORDER_TIMEOUT: 'order.timeout',
  ORDER_FEEDBACK_REMINDER: 'order.feedback_reminder',
  COURIER_DISPATCH: 'courier.dispatch',
  COURIER_STALE_CHECK: 'courier.stale_check',
  SETTLEMENT_CRON: 'settlement.cron',
  SETTLEMENT_GENERATE: 'settlement.generate',
  DWELL_MONITOR: 'dwell.monitor',
  ANONYMIZER_RETENTION: 'anonymizer.retention',
  ANONYMIZER_GDPR: 'anonymizer.gdpr',
  VELOCITY_FLUSH: 'velocity.flush',
  FREE_TIER_WATCH: 'free_tier.watch',
  SIGNAL_RAISER: 'signal.raiser',
  LIVENESS_CHECK: 'liveness.check',
  GPS_PURGE: 'gps.purge',
  BACKUP_HOURLY: 'backup.hourly',
  BACKUP_DAILY: 'backup.daily',
  BACKUP_WEEKLY: 'backup.weekly',
  BACKUP_MONTHLY: 'backup.monthly',
  BACKUP_VERIFY_RESTORE: 'backup.verify.restore',
  BACKUP_VERIFY_R2: 'backup.verify.r2',
  RECONCILIATION_NIGHTLY: 'reconciliation.nightly',
  RATES_REFRESH: 'rates.refresh',
} as const;
