import { loadEnv } from '@deliveryos/config';
import { createSessionPool } from '@deliveryos/db';
loadEnv();
const pool = createSessionPool();
const r = await pool.query(`SELECT column_name, is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'locations' ORDER BY ordinal_position`);
console.log('locations columns:');
r.rows.forEach(row => console.log(`  ${row.column_name} (nullable: ${row.is_nullable})`));
const r2 = await pool.query(`SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid = 'public.locations'::regclass AND contype = 'u'`);
console.log('\nUnique constraints:');
r2.rows.forEach(row => console.log(`  ${row.conname}: ${row.pg_get_constraintdef}`));
await pool.end();
