//! PURE. A DISH'S TASTE DRAFTED FROM ITS RECIPE: the harmonic extension of the declared dishes'
//! vectors over the dish--supply graph (W-TASTE2, S7b; R-S7 research 2026-10-06 §E2, operator:
//! "S7b harmonic Suggest built now, ready for when recipes exist"; "sheaf calculus" read as the
//! Hansen--Ghrist sheaf Laplacian).
//!
//! THE MODEL. Nodes are the venue's dishes and the supplies their recipes use; a recipe line joins
//! a dish to a supply with the weight of its SHARE of that recipe (Q16). Every dish whose taste the
//! kitchen declared is a fixed value (its `sense::vector`, per mille, 27 keys); every other node --
//! the dish being drafted, every supply, every undeclared dish -- takes the weighted mean of its
//! neighbours. That is the minimiser of the sheaf Dirichlet energy for the constant sheaf with
//! these edge weights (E2's B2/B3 family), found by Gauss--Seidel: each update is an exact
//! minimiser of its own terms. Integers only: Q16 values, i128 sums, round-half-up division --
//! E2 measured the Q16 run equal to f64 within 1 per mille.
//!
//! HONEST ABOUT WHAT IT IS (E2): 5.4% better than the plain mean of neighbouring dishes, on
//! synthetic data generated by this very model; below the 10% bar set before the run. So it is a
//! SECOND SOURCE for "Suggest", marked `from = recipe`, never written by itself, always reviewed by
//! the owner. With no recipes it says so ([`Draft::NoRecipes`]) and invents nothing: on 2026-10-06
//! both live venues have 0 recipes. Supplies of different units are weighted by quantity share as
//! E2 was; categories (E2's third node kind) are not in the blocks this reads and are left out.
//! Bounded: at most [`PASSES`] sweeps (E2: 200 passes = 20 ms in Q16, too long for a 10 ms Worker);
//! it stops early when a sweep changes nothing and reports how many it used.

use std::collections::{BTreeMap, HashMap, VecDeque};

use super::{all_keys, Dim, Sense, SCALE};

/// Gauss--Seidel sweeps at most.
pub const PASSES: usize = 60;
const Q: i64 = 1 << 16;
const KEYS: usize = 27;

/// One dish as this reads it: id, recipe lines `(supply, qty)`, declared vector (if any).
pub type DishIn = (String, Vec<(String, i64)>, Option<BTreeMap<String, i64>>);

/// What the recipe graph can say about one dish.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Draft {
    /// No dish of the venue has a recipe: there is no graph.
    NoRecipes,
    /// This dish has no recipe (or is not on the menu).
    NoRecipe,
    /// Its recipe shares no supply, through any chain, with a dish whose taste is declared.
    NoNeighbours,
    /// The harmonic value at the dish, per mille per key (zeros left out), the declared dishes it
    /// was drawn from, and the sweeps used.
    From { vector: BTreeMap<String, i64>, neighbours: usize, passes: usize },
}

impl Draft {
    pub fn word(&self) -> &'static str {
        match self {
            Draft::NoRecipes => "no-recipes",
            Draft::NoRecipe => "no-recipe",
            Draft::NoNeighbours => "no-neighbours",
            Draft::From { .. } => "drafted",
        }
    }
}

fn div_round(n: i128, d: i128) -> i64 {
    ((2 * n + d) / (2 * d)) as i64
}

/// The harmonic extension at `target`.
pub fn extend(dishes: &[DishIn], target: &str, max_passes: usize) -> Draft {
    if dishes.iter().all(|(_, bom, _)| bom.iter().all(|(_, q)| *q <= 0)) {
        return Draft::NoRecipes;
    }
    let Some(t) = dishes.iter().position(|(id, bom, _)| id == target && bom.iter().any(|(_, q)| *q > 0)) else {
        return Draft::NoRecipe;
    };
    // Nodes: dishes 0..n, then supplies. Edges: (dish, supply, Q16 share), duplicates summed.
    let n = dishes.len();
    let mut supply: HashMap<&str, usize> = HashMap::new();
    let mut adj: Vec<Vec<(usize, i64)>> = vec![Vec::new(); n];
    for (d, (_, bom, _)) in dishes.iter().enumerate() {
        let total: i64 = bom.iter().map(|(_, q)| (*q).max(0)).sum();
        if total <= 0 {
            continue;
        }
        let mut lines: BTreeMap<&str, i64> = BTreeMap::new();
        for (s, q) in bom.iter().filter(|(_, q)| *q > 0) {
            *lines.entry(s.as_str()).or_default() += *q;
        }
        for (s, q) in lines {
            let w = (i128::from(q) * i128::from(Q) / i128::from(total)).max(1) as i64;
            let at = *supply.entry(s).or_insert_with(|| {
                adj.push(Vec::new());
                adj.len() - 1
            });
            adj[d].push((at, w));
            adj[at].push((d, w));
        }
    }
    let keys = all_keys();
    let fixed: Vec<Option<[i64; KEYS]>> = (0..adj.len())
        .map(|v| {
            let vec = (v < n && v != t).then(|| dishes[v].2.as_ref()).flatten().filter(|m| m.values().any(|x| *x > 0))?;
            let mut row = [0i64; KEYS];
            for (i, k) in keys.iter().enumerate() {
                row[i] = vec.get(k).copied().unwrap_or(0).clamp(0, SCALE) * Q;
            }
            Some(row)
        })
        .collect();
    // The component of `target`, in index order, and the declared dishes in it.
    let mut seen = vec![false; adj.len()];
    let mut queue = VecDeque::from([t]);
    seen[t] = true;
    while let Some(v) = queue.pop_front() {
        if fixed[v].is_some() {
            continue; // a declared dish is a boundary: the extension does not pass through it
        }
        for &(u, _) in &adj[v] {
            if !seen[u] {
                seen[u] = true;
                queue.push_back(u);
            }
        }
    }
    let boundary: Vec<usize> = (0..adj.len()).filter(|v| seen[*v] && fixed[*v].is_some()).collect();
    if boundary.is_empty() {
        return Draft::NoNeighbours;
    }
    let free: Vec<usize> = (0..adj.len()).filter(|v| seen[*v] && fixed[*v].is_none()).collect();
    // Start every free node at the mean of the boundary: fewer sweeps, the same fixed point.
    let mut mean = [0i64; KEYS];
    for (i, m) in mean.iter_mut().enumerate() {
        let s: i128 = boundary.iter().map(|v| i128::from(fixed[*v].unwrap()[i])).sum();
        *m = div_round(s, boundary.len() as i128);
    }
    let mut x: Vec<[i64; KEYS]> = (0..adj.len()).map(|v| fixed[v].unwrap_or(mean)).collect();
    let mut passes = max_passes;
    for pass in 0..max_passes {
        let mut moved = false;
        for &v in &free {
            let den: i128 = adj[v].iter().map(|(_, w)| i128::from(*w)).sum();
            if den == 0 {
                continue;
            }
            for i in 0..KEYS {
                let num: i128 = adj[v].iter().map(|(u, w)| i128::from(*w) * i128::from(x[*u][i])).sum();
                let new = div_round(num, den);
                if new != x[v][i] {
                    x[v][i] = new;
                    moved = true;
                }
            }
        }
        if !moved {
            passes = pass + 1;
            break;
        }
    }
    let vector = keys.iter().enumerate().map(|(i, k)| (k.clone(), div_round(i128::from(x[t][i]), i128::from(Q)))).filter(|(_, v)| *v > 0).collect();
    Draft::From { vector, neighbours: boundary.len(), passes }
}

/// A drafted vector as a stored-shape profile: a taste axis at round(pm x 5 / 1000) when that is
/// at least 1, a texture or aroma at round(pm x 3 / 1000) when at least 1. Never a 0 taste claim:
/// "not spicy" is the kitchen's to say, not an average's.
pub fn to_sense(vector: &BTreeMap<String, i64>) -> Sense {
    let mut s = Sense::default();
    for d in Dim::ALL {
        for w in d.words() {
            let pm = vector.get(&format!("{}:{w}", d.prefix())).copied().unwrap_or(0).clamp(0, SCALE);
            let level = (pm * d.max() + SCALE / 2) / SCALE;
            if level >= 1 {
                s.map_mut(d).insert(w.to_string(), level);
            }
        }
    }
    s
}

/// The venue's dishes as the two blocks hold them: ids and declared vectors from `taste.dwb`,
/// recipes from the catalogue projection's `bom` (`view::Catalogue::bom_of`).
pub fn dishes_of(taste: &crate::block::view::View, cat: &crate::block::view::Catalogue) -> Vec<DishIn> {
    (0..taste.n())
        .filter_map(|row| {
            let id = taste.str_at(row)?.to_string();
            let bom = cat.bom_of(&id).unwrap_or_default().into_iter().map(|l| (l.supply, l.qty)).collect();
            let v = crate::block::taste::vector_at(taste, row);
            Some((id, bom, (!v.is_empty()).then_some(v)))
        })
        .collect()
}

#[cfg(test)]
#[path = "harmonic_tests.rs"]
mod tests;
