#!/usr/bin/env python3
"""gen_scan.py — B2 decisive twin (ii): specialise-then-run scan template writer
(docs/blueprints/B2-decisive-twins.md §3(ii)). Emits a self-contained scan_<digest>.bp source
(compiled and run separately by the driver, which measures the compile wall time — the
"specialise" step) for ONE concrete schema+predicate: 3 i64 columns, `c0 in [LO,HI) and
c1 < Q`, `sum(c2)`, over N rows generated by the same LCG stream as
bench/oracles/scan_twin.py / bench/vs_rust/rust_once/scan_const.rs|scan_generic.rs.

Deliberately python, not a .bp generator (the blueprint's own text allows either: "a tiny
generator gen_scan.bp (or python for now, blueprint decides)"). The gate this feeds
(bebop_total(compile+run) <= rust_generic/5) times the COMPILE and RUN of the generated
program, not the template expansion, so a python templater changes nothing about what's
measured; a native .bp generator can replace this later without touching the gate math
(see bench/vs_rust/B2-PREP.md).

digest = md5 of (n, LO, HI, Q, SEED) so distinct N's get distinct filenames (a memo-hit re-run
just skips regenerating/recompiling an existing scan_<digest>.bin — "row B: run only").

CLI: python3 gen_scan.py <n> > scan_<digest>.bp   (or with -o <path> to write directly)
"""
import hashlib
import sys

LO, HI, Q = 200000, 500000, 500
SEED = 5591

TEMPLATE = """// scan_{digest} — generated by bench/vs_rust/std_tests/gen_scan.py (B2 twin ii):
// specialised scan, N={n} rows, predicate c0 in [{lo},{hi}) and c1 < {q}, aggregate sum(c2).
// Do not hand-edit — regenerate from gen_scan.py if the schema/predicate/N changes.
fn lcg(x: i64) -> i64 {{ x * 6364136223846793005 + 1442695040888963407 }}
fn main() -> i64 {{
  let n = {n};
  let x = {seed};
  let sum = 0;
  let i = 0;
  while i < n {{
    let x = lcg(x);
    let c0 = (x >> 20) % 1000000;
    let x = lcg(x);
    let c1 = (x >> 40) % 1000;
    let x = lcg(x);
    let c2 = (x >> 10) % 1000000;
    let inrange = (if c0 >= {lo} then 1 else 0) * (if c0 < {hi} then 1 else 0) * (if c1 < {q} then 1 else 0);
    let sum = sum + inrange * c2;
    let i = i + 1;
    0
  }};
  sum
}}
"""


def digest_for(n):
    h = hashlib.md5(f'{n}:{LO}:{HI}:{Q}:{SEED}'.encode()).hexdigest()[:8]
    return h


def render(n):
    d = digest_for(n)
    return d, TEMPLATE.format(digest=d, n=n, seed=SEED, lo=LO, hi=HI, q=Q)


if __name__ == '__main__':
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20000
    out = None
    if '-o' in sys.argv:
        out = sys.argv[sys.argv.index('-o') + 1]
    d, src = render(n)
    if out:
        with open(out, 'w') as f:
            f.write(src)
        print(d)
    else:
        sys.stdout.write(src)
