#!/usr/bin/env python3
"""gen_scan.py — B2 decisive twin (ii): specialise-then-run scan template writer
(docs/blueprints/B2-decisive-twins.md §3(ii)). Emits a self-contained scan_<digest>.bp source
(compiled and run separately by the driver, which measures the compile wall time — the
"specialise" step) for ONE concrete schema+predicate: 3 i64 columns, `c0 in [LO,HI) and
c1 < Q`, `sum(c2)`, over N rows.

WHAT CHANGED 2026-09-08 (and why it matters to the gate). The first version of this template
generated each row inside the timed loop from the LCG and filtered it on the fly. That timed a
random-number generator with a predicate stapled to it, not a scan: three multiply-add LCG
steps per row swamped the three column loads a scan actually performs, and the swamping was
symmetric, so the very quantity the row exists to expose — what specialising the predicate is
worth against interpreting it — was diluted into the noise of a shared arithmetic constant.
The table is now MATERIALISED FIRST into three i64 column arrays (c0,c1,c2), untimed, and only
the pass over those arrays is timed. That is what a scan is, and it is what the Rust twins
(scan_const.rs, scan_generic.rs) now do too. The generated row values are bit-identical to
before — same LCG stream, same constants, same order — so bench/oracles/scan_twin.py's sum is
unchanged and remains the oracle for all three engines.

REPS: bench/vs_rust/kernel_reps.txt's rule is that a timed run must last ~100 ms or it measured
the box, not the code. One 1M-row scan is ~1 ms, so the generated program takes a rep count in
argv and reports the PER-REP median; the reps are a measurement technique on a pure function,
not part of the latency being claimed. Latency-to-result is then (compile wall) + (one scan).

argv of the generated program (seed's argv[0]/[1] are "seed"/the binary path; user args from [2]):
  argv[2] = mode: 's' = the sum (the fold), 't' = scan ms for `reps` reps / reps
  argv[3] = reps
N, the schema, the predicate and the aggregate are BAKED IN — that is the specialisation whose
compile time the gate charges bebop for.

Deliberately python, not a .bp generator (the blueprint's own text allows either). The gate
times the COMPILE and RUN of the generated program, not the template expansion, so a python
templater changes nothing about what is measured; a native .bp generator can replace this later
without touching the gate math (see bench/vs_rust/B2-PREP.md).

digest = md5 of (n, LO, HI, Q, SEED) so distinct N's get distinct filenames (a memo-hit re-run
just skips regenerating/recompiling an existing scan_<digest>.bin — "row B: run only").

CLI: python3 gen_scan.py <n> > scan_<digest>.bp   (or with -o <path> to write directly)
"""
import hashlib
import sys

LO, HI, Q = 200000, 500000, 500
SEED = 5591

TEMPLATE = """// scan_{digest} — generated by bench/vs_rust/std_tests/gen_scan.py (B2 twin ii):
// specialised scan over a materialised 3-column table, N={n} rows, predicate
// c0 in [{lo},{hi}) and c1 < {q}, aggregate sum(c2). The table is built once (untimed); only
// the pass over the columns is timed, `reps` times, and mode 't' reports the per-rep ms.
// Do not hand-edit — regenerate from gen_scan.py if the schema/predicate/N changes.
fn lcg(x: i64) -> i64 {{ x * 6364136223846793005 + 1442695040888963407 }}

fn parse(s: str) -> i64 {{
  let n = str_len(s);
  let i = 0;
  let v = 0;
  while i < n {{
    let v = v * 10 + (char(s, i) - 48);
    let i = i + 1;
    0
  }};
  v
}}

// Materialise the table: one continuous LCG stream, 3 draws per row, columns stored
// column-major. Identical value stream to bench/oracles/scan_twin.py and the Rust twins.
fn fill(n: i64, c0: [i64], c1: [i64], c2: [i64]) -> i64 {{
  let x = {seed};
  let i = 0;
  while i < n {{
    let x = lcg(x);
    let _ = c0[i] = (x >> 20) % 1000000;
    let x = lcg(x);
    let _ = c1[i] = (x >> 40) % 1000;
    let x = lcg(x);
    let _ = c2[i] = (x >> 10) % 1000000;
    let i = i + 1;
    0
  }};
  0
}}

// The specialised kernel: every bound is a literal the compiler saw, the predicate is
// branchless (the same shape scan_const.rs's `(c0>=LO) as i64 * ...` compiles to), and the
// aggregate column is fixed. Nothing here is read from a descriptor at run time — that is the
// whole point of the row.
fn b2_scan(n: i64, c0: [i64], c1: [i64], c2: [i64]) -> i64 {{
  let sum = 0;
  let i = 0;
  while i < n {{
    let v = c0[i];
    let lo_ok = if v >= {lo} then 1 else 0;
    let hi_ok = if v < {hi} then 1 else 0;
    let q_ok = if c1[i] < {q} then 1 else 0;
    let sum = sum + lo_ok * hi_ok * q_ok * c2[i];
    let i = i + 1;
    0
  }};
  sum
}}

fn main(argc: i64, argv: [str]) -> i64 {{
  let n = {n};
  let mode = char(argv[2], 0);
  let reps = parse(argv[3]);
  let c0 = zeros(n);
  let c1 = zeros(n);
  let c2 = zeros(n);
  let _ = fill(n, c0, c1, c2);
  // sm is a cell, not a rebind: it carries the kernel's result across the rep loop, and
  // cross-loop state lives in cells here (join_twin.bp's probe carries the same note).
  let sm = zeros(1);
  let t0 = clock_ms();
  let r = 0;
  while r < reps {{
    let _ = sm[0] = b2_scan(n, c0, c1, c2);
    let r = r + 1;
    0
  }};
  let t1 = clock_ms();
  // TOTAL ms for all reps, not the per-rep quotient: clock_ms is 1 ms coarse (K1h), so
  // dividing inside would quantise the answer to whole milliseconds. The driver divides.
  if mode == 116 then t1 - t0 else sm[0]
}}
"""


def digest_for(n):
    h = hashlib.md5(f'{n}:{LO}:{HI}:{Q}:{SEED}'.encode()).hexdigest()[:8]
    return h


def render(n):
    d = digest_for(n)
    return d, TEMPLATE.format(digest=d, n=n, seed=SEED, lo=LO, hi=HI, q=Q)


if __name__ == '__main__':
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20000
    out = None
    if '-o' in sys.argv:
        out = sys.argv[sys.argv.index('-o') + 1]
    d, src = render(n)
    if out:
        with open(out, 'w') as f:
            f.write(src)
        print(d)
    else:
        sys.stdout.write(src)
