/**
 * GENERATED by scripts/rebuild-cutover/gen-node-keep.mjs — DO NOT EDIT.
 *
 * Mapped routes whose surface may be flipped to Rust while the route itself has NO Rust
 * mount yet: the front-door keeps these on Node regardless of the surface flag (per-route
 * strangler). Regenerate whenever the Rust surface grows; entries disappearing from this
 * file IS the strangler making progress. Deliberately-retired ops (courier/activate) are
 * excluded — their Rust 404 is the port.
 *
 * Per-surface unmounted counts: {"S10":5,"S1":1,"S2":2,"S3":13,"S5":23,"S8":17}
 */
export const NODE_KEEP_ROUTES: ReadonlySet<string> = new Set([
  'GET /api/owner/activation/:locationId/status', // S10
  'POST /api/owner/activation/:locationId/pickup', // S10
  'POST /api/owner/activation/:locationId/publish', // S10
  'POST /api/owner/onboarding', // S10
  'POST /api/owner/onboarding/start', // S10
  'GET /branding-preview/:slug', // S1
  'POST /api/customer/locations/:slug/otp/send', // S2
  'POST /api/customer/locations/:slug/otp/verify', // S2
  'DELETE /api/owner/promotions/:id', // S3
  'GET /api/owner/brand', // S3
  'GET /api/owner/promotions', // S3
  'GET /api/owner/promotions/:id', // S3
  'PATCH /api/owner/promotions/:id', // S3
  'POST /api/owner/brand/generate', // S3
  'POST /api/owner/locations/:id/menu/translate', // S3
  'POST /api/owner/menu/import/anonymous', // S3
  'POST /api/owner/menu/import/commit', // S3
  'POST /api/owner/menu/import/preview', // S3
  'POST /api/owner/promotions', // S3
  'POST /api/owner/promotions/validate', // S3
  'PUT /api/owner/brand', // S3
  'GET /api/customer/orders/:orderId/status', // S5
  'GET /api/orders/:orderId/messages', // S5
  'GET /api/owner/:locationId/refunds', // S5
  'GET /api/owner/locations/:locationId/dashboard/snapshot', // S5
  'GET /api/owner/locations/:locationId/orders/:orderId/verify', // S5
  'GET /api/owner/locations/:locationId/settlements', // S5
  'GET /api/owner/locations/:locationId/settlements/:id', // S5
  'GET /api/owner/orders', // S5
  'POST /api/customer/orders/:orderId/rating', // S5
  'POST /api/orders/:orderId/messages', // S5
  'POST /api/orders/:orderId/messages/read', // S5
  'POST /api/owner/:locationId/refunds/:paymentId/sent', // S5
  'POST /api/owner/locations/:locationId/orders/:orderId/assign-courier', // S5
  'POST /api/owner/locations/:locationId/orders/:orderId/deliver', // S5
  'POST /api/owner/locations/:locationId/orders/:orderId/mark-no-show', // S5
  'POST /api/owner/locations/:locationId/orders/:orderId/pickup', // S5
  'POST /api/owner/locations/:locationId/orders/:orderId/reveal-customer-contact', // S5
  'POST /api/owner/locations/:locationId/settlements/:id/approve', // S5
  'POST /api/owner/locations/:locationId/settlements/:id/dispute', // S5
  'POST /api/owner/locations/:locationId/settlements/:id/pay', // S5
  'POST /api/owner/locations/:locationId/settlements/:id/reopen', // S5
  'POST /api/owner/locations/:locationId/settlements/regenerate', // S5
  'POST /webhook/payments/plisio', // S5
  'GET /api/owner/locations/:locationId/alerts', // S8
  'GET /api/owner/locations/:locationId/notifications/status', // S8
  'GET /api/owner/locations/:locationId/notifications/targets', // S8
  'GET /api/owner/locations/:locationId/push/state', // S8
  'GET /api/owner/locations/:locationId/signals', // S8
  'GET /api/owner/locations/:locationId/signals/compute', // S8
  'POST /api/customer/push/subscribe', // S8
  'POST /api/customer/push/unsubscribe', // S8
  'POST /api/owner/locations/:locationId/alerts/:alertId/acknowledge', // S8
  'POST /api/owner/locations/:locationId/alerts/acknowledge-all', // S8
  'POST /api/owner/locations/:locationId/notifications/telegram/connect-init', // S8
  'POST /api/owner/locations/:locationId/notifications/test', // S8
  'POST /api/owner/locations/:locationId/push/subscribe', // S8
  'POST /api/owner/locations/:locationId/push/unsubscribe', // S8
  'POST /api/owner/locations/:locationId/signals/:signalId/acknowledge', // S8
  'POST /api/owner/locations/:locationId/signals/:signalId/dismiss', // S8
  'PUT /api/owner/locations/:locationId/notifications/targets/:targetId', // S8
]);
