/* Bebop Modular — PSL(2,Z) Möbius transformations (port of dowiz modular.rs).
 * Fractional-linear maps z ↦ (az+b)/(cz+d) with det ad−bc = 1, generated by
 * S: z↦−1/z and T: z↦z+1. */
#ifndef BEBOP_MODULAR_H
#define BEBOP_MODULAR_H

#include <stdint.h>
#include <stddef.h>

#include "complex.h"

typedef struct {
    int64_t a, b, c, d;
} Mobius;

Mobius mobius_identity(void);
Mobius mobius_s(void); /* z ↦ −1/z */
Mobius mobius_t(void); /* z ↦ z+1 */
int64_t mobius_det(Mobius m);
Complex mobius_apply(Mobius m, Complex z);
Mobius mobius_compose(Mobius m, Mobius o); /* m ∘ o */

int mobius_in_fundamental_domain(Complex z);
Complex mobius_reduce(Complex z, int max_iter);

int modular_self_test(char *out, size_t cap);

#endif /* BEBOP_MODULAR_H */
