#!/usr/bin/env python3
"""Rebuild public/kit/icons.js from the exported SVGs in public/kit/icon/.

Lives OUTSIDE public/ because everything under public/ is served: a build
script and a 22MB design dump have no business being fetchable.

Run after adding assets for a new screen. The path data is EXACTLY what Figma
exported -- nothing is redrawn. Only the kit's neutral fills and strokes become
currentColor, because the same glyph ships in a light and a dark frame and only
its fill differs; brand colours stay literal, since they mean the same thing in
both themes.
"""
import re, os, io, json

NEUTRAL = {'#8A8A8A', '#B0B0B0', '#E0E0E0', '#A8A8A8', 'WHITE', '#FFFFFF', '#010101', '#2A2A2A'}

# Figma's export puts CSS in `style=` attributes. Those are INLINE STYLE
# ATTRIBUTES, and `style-src 'self'` in public/_headers blocks every one of
# them — found in a real browser, where the sprite reported three
# `style-src-attr` violations per page and any icon relying on `mask-type`
# rendered wrong. jsdom applies no CSP and saw nothing.
#
# The declarations that MATTER have SVG presentation attributes; the rest are
# cosmetic and are dropped rather than smuggled back in.
STYLE_TO_ATTR = {
    'mask-type': 'mask-type',
}
DROP_DECLS = {'display', 'backdrop-filter', 'clip-path', 'mix-blend-mode'}

def destyle(markup):
    """Turn every `style="..."` into presentation attributes or nothing."""
    def one(mo):
        out = []
        for decl in mo.group(1).split(';'):
            if ':' not in decl:
                continue
            k, v = decl.split(':', 1)
            k, v = k.strip().lower(), v.strip()
            if k in DROP_DECLS or not v:
                continue
            attr = STYLE_TO_ATTR.get(k)
            if attr:
                out.append(f'{attr}="{v}"')
            # Anything else is dropped on purpose: a declaration with no SVG
            # attribute equivalent cannot be carried without an inline style.
        return (' ' + ' '.join(out)) if out else ''
    return re.sub(r'\s*style="([^"]*)"', one, markup)
HEADER = '''// The kit's icons, exported from Figma and inlined as one sprite.
// GENERATED by kit/build-sprite.py -- do not hand-edit; add an SVG to kit/icon/
// and re-run it from anywhere.
//
// WHY A SPRITE AND NOT <img src="icon.svg">. An <img> cannot be recoloured, and
// this kit ships the same glyph in two themes with identical geometry. So each
// icon's PATH DATA is exactly Figma's export and only the neutral fills and
// strokes are rewritten to currentColor.
//
// Cross-document <use href="file.svg#id"> is unreliable, so the sprite is put
// into the document once and referenced with a same-document fragment.
'''

def localise_ids(body, sym):
    """Make every id in one symbol local to it, and drop the ones nobody uses.

    TWO DEFECTS, ONE PASS.

    The first is latent and would be very hard to see: Figma numbers a gradient
    or a clip path per FILE (`clip0_0_67`), so two icons exported from the same
    board can carry the same id. In separate files that is fine. In one sprite
    it is not -- a `url(#clip0_0_67)` resolves to whichever symbol the document
    reached first, and one icon silently renders with another's clip. There is
    no collision in the current 124 icons, measured; there is nothing stopping
    the next export from adding one. So every id becomes `<symbol>-<id>` and
    every reference to it is rewritten in the same pass.

    The second is visible now: Figma writes its LAYER NAMES out as ids, so the
    sprite carries `id="Vector"` 78 times and `id="Stroke 3"` three times. They
    reference nothing; they just make every id in the document a duplicate,
    which an interaction audit reports as a double render and which makes
    `getElementById` in the app a coin toss. Unreferenced ids are removed.
    """
    refs = set(re.findall(r'url\(#([^)]+)\)', body))
    refs |= set(re.findall(r'(?:xlink:)?href="#([^"]+)"', body))

    def rename(mo):
        name = mo.group(1)
        # The leading space is not cosmetic: the regex consumed it, so dropping
        # it welds the attribute onto the tag name -- `<clipPathid="...">`.
        return f' id="{sym}-{name}"' if name in refs else ''

    body = re.sub(r'\s*id="([^"]+)"', rename, body)
    for name in refs:
        body = body.replace(f'url(#{name})', f'url(#{sym}-{name})')
        body = body.replace(f'href="#{name}"', f'href="#{sym}-{name}"')
    return body


syms, swaps = [], 0
KIT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'kit')
for f in sorted(os.listdir(os.path.join(KIT, 'icon'))):
    if not f.endswith('.svg'): continue
    s = io.open(os.path.join(KIT, 'icon', f), encoding='utf-8').read()
    m = re.search(r'viewBox="([^"]+)"', s)
    vb = m.group(1) if m else '0 0 24 24'
    body = s[s.index('>', s.index('<svg')) + 1:s.rindex('</svg>')]
    body = destyle(body)
    def sub(mo):
        global swaps
        if mo.group(2).upper() in NEUTRAL:
            swaps += 1
            return f'{mo.group(1)}="currentColor"'
        return mo.group(0)
    body = re.sub(r'\b(fill|stroke)="(#[0-9a-fA-F]{3,8}|white|black)"', sub, body)
    body = localise_ids(body, f[:-4])
    syms.append(f'<symbol id="i-{f[:-4]}" viewBox="{vb}" fill="none">{body}</symbol>')

# The sprite's own wrapper carried `style="display:none"` — which is exactly the
# same violation. It is hidden by its host element instead.
sprite = ('<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">'
          + ''.join(syms) + '</svg>')
io.open(os.path.join(KIT, 'icons.js'), 'w', encoding='utf-8').write(HEADER + f'''export const SPRITE = {json.dumps(sprite)};

export function mountSprite(){{
  if (document.getElementById('kit-sprite')) return;
  const host = document.createElement('div');
  host.id = 'kit-sprite';
  host.hidden = true;
  host.innerHTML = SPRITE;
  document.body.prepend(host);
}}

// `focusable="false"` keeps IE-era SVG out of the tab order; `aria-hidden`
// because every icon here sits next to its own label or inside a titled button.
export const icon = (name, cls = '') =>
  `<svg class="ic ${{cls}}" aria-hidden="true" focusable="false"><use href="#i-${{name}}"/></svg>`;
''')
print(f'{len(syms)} symbols, {swaps} currentColor swaps, sprite {len(sprite)} bytes')
