//! engine.rs — native port of static_runner.run_static_patterns + friends.
//!
//! Faithful 1:1 behavior: file-type inference, binary/eval-dataset skip,
//! documentation-markdown + code-example confidence downweighting, PE3 .env
//! doc-reference filter. The regex set + DEFAULT_* metadata come from rules.rs
//! (generated by gen_rules.py from the upstream Python).

use crate::rules::{CATEGORIES, EXPLANATIONS, NAMES, REMEDIATIONS, RULES};
use regex::Regex;
use std::collections::HashMap;

/// A single emitted finding (graph-state `Finding` shape).
#[derive(Debug, Clone, serde::Serialize)]
pub struct Finding {
    pub id: String,
    pub category: Option<String>,
    pub pattern: Option<String>,
    pub severity: String,
    pub confidence: f64,
    pub location: Location,
    pub finding: Option<String>,
    pub explanation: Option<String>,
    pub remediation: Option<String>,
    pub code_snippet: Option<String>,
    pub intent: Option<String>,
    pub tags: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct Location {
    pub file: String,
    pub start_line: usize,
    pub end_line: Option<usize>,
}

const MAX_FILE_BYTES: usize = 1_000_000;

const FILE_TYPES: &[(&str, &str)] = &[
    (".md", "markdown"),
    (".markdown", "markdown"),
    (".py", "python"),
    (".sh", "shell"),
    (".bash", "shell"),
    (".zsh", "shell"),
    (".json", "json"),
    (".yaml", "yaml"),
    (".yml", "yaml"),
    (".toml", "toml"),
    (".txt", "text"),
    (".js", "javascript"),
    (".ts", "typescript"),
    (".rb", "ruby"),
    (".go", "go"),
    (".rs", "rust"),
];

const BINARY_EXTS: &[&str] = &[
    ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".woff", ".woff2",
    ".ttf", ".otf", ".eot", ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".exe", ".dll", ".so", ".dylib", ".bin", ".o", ".a", ".pyc", ".pyo", ".class",
    ".wasm", ".mp3", ".mp4", ".wav", ".avi", ".mov", ".webm", ".sqlite", ".db",
];

const EVAL_DATASETS: &[&str] = &[
    "evals/evals.json",
    "evals/evals.jsonl",
    "evals/evals.yaml",
    "evals/evals.yml",
    "eval/dataset.json",
    "eval/dataset.jsonl",
    "eval/dataset.yaml",
    "eval/dataset.yml",
];

const DOC_DIR_NAMES: &[&str] = &[
    "docs", "documentation", "procedures", "references", "examples", "guides",
];

const CODE_EXAMPLE_INDICATORS: &[&str] = &[
    "```", "example:", "for example", "e.g.", "such as", "documentation",
    "# warning:", "# note:", "**warning**", "**note**", "// ✅", "// ❌",
    "// good:", "// bad:", "// correct:", "// incorrect:", "// wrong:",
];

const DOC_CONFIDENCE_FACTOR: f64 = 0.3;
const CODE_EXAMPLE_CONFIDENCE_FACTOR: f64 = 0.5;
const NON_EXEC_FILE_TYPES: &[&str] = &["markdown", "text", "json", "yaml", "toml", "other"];

fn infer_file_type(path: &str) -> String {
    let idx = path.rfind('.').unwrap_or(path.len());
    let suffix = if idx < path.len() {
        path[idx..].to_lowercase()
    } else {
        String::new()
    };
    for (ext, ft) in FILE_TYPES {
        if *ext == suffix {
            return ft.to_string();
        }
    }
    "other".to_string()
}

fn is_binary_file(path: &str, content: &str) -> bool {
    let idx = path.rfind('.').unwrap_or(path.len());
    if idx < path.len() {
        let suffix = path[idx..].to_lowercase();
        if BINARY_EXTS.contains(&suffix.as_str()) {
            return true;
        }
    }
    content[..content.len().min(512)].contains('\u{0}')
}

fn is_eval_dataset(path: &str) -> bool {
    let norm = path.replace('\\', "/").to_lowercase();
    EVAL_DATASETS.contains(&norm.as_str())
}

fn is_documentation_markdown(path: &str) -> bool {
    let norm = path.replace('\\', "/").to_lowercase();
    if !(norm.ends_with(".md") || norm.ends_with(".markdown")) {
        return false;
    }
    if norm.ends_with("skill.md") {
        return false;
    }
    let parts: Vec<&str> = norm.split('/').collect();
    parts[..parts.len().saturating_sub(1)]
        .iter()
        .any(|p| DOC_DIR_NAMES.contains(p))
}

fn is_code_example(context: &str) -> bool {
    let ctx = context.to_lowercase();
    CODE_EXAMPLE_INDICATORS.iter().any(|ind| ctx.contains(*ind))
}

// PE3 .env doc-reference filter (mirrors _is_env_file_reference_in_docs).
const PE3_ENV_REFERENCE: &str = r"(?i)(create|copy|rename|add|set up|configure|make)\s+.*\.env";
const PE3_DOC_PHRASES: &[&str] = &[
    ".env.example", "cp .env", "copy .env", "mv .env", "rename .env",
    ".env file", "environment file", "dotenv",
];

fn is_env_file_reference_in_docs(rule_id: &str, file_type: &str, file_path: &str, context: &str) -> bool {
    if rule_id != "PE3" {
        return false;
    }
    if !matches!(file_type, "markdown" | "text") {
        return false;
    }
    if file_path.replace('\\', "/").to_lowercase().ends_with("skill.md") {
        return false;
    }
    if context.is_empty() {
        return false;
    }
    if Regex::new(PE3_ENV_REFERENCE).unwrap().is_match(context) {
        return true;
    }
    let ctx = context.to_lowercase();
    PE3_DOC_PHRASES.iter().any(|p| ctx.contains(*p))
}

fn lookup<'a>(table: &'a [(&str, &str)], key: &str) -> Option<&'a str> {
    table.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}

/// Scan a single file's content, returning findings (one per regex match).
pub fn scan_file(path: &str, content: &str) -> Vec<Finding> {
    let mut findings = Vec::new();
    if is_eval_dataset(path) {
        return findings;
    }
    if content.len() > MAX_FILE_BYTES {
        return findings;
    }
    // Precompile all rules once (module-level cache would be ideal; vec is small enough).
    let compiled: Vec<(String, Regex, f64)> = RULES
        .iter()
        .filter_map(|r| Regex::new(r.regex).ok().map(|re| (r.rule_id.to_string(), re, r.conf)))
        .collect();

    let file_type = infer_file_type(path);
    let is_doc_md = is_documentation_markdown(path);
    let is_non_exec = NON_EXEC_FILE_TYPES.contains(&file_type.as_str());
    let lines: Vec<&str> = content.split_inclusive('\n').collect();

    for (rule_id, re, base_conf) in &compiled {
        for m in re.find_iter(content) {
            let mtext = &content[m.start()..m.end()];
            let start_line = content[..m.start()].matches('\n').count() + 1;
            let context = extract_context(content, m.start());
            let mut conf = *base_conf;

            // PE3 doc-reference filter
            if is_env_file_reference_in_docs(rule_id, &file_type, path, &context) {
                continue;
            }
            if !context.is_empty() && is_code_example(&context) {
                if is_non_exec {
                    continue;
                }
                conf *= CODE_EXAMPLE_CONFIDENCE_FACTOR;
            }
            if is_doc_md {
                conf *= DOC_CONFIDENCE_FACTOR;
            }

            let category = lookup(CATEGORIES, rule_id).map(|s| s.to_string());
            let pattern = lookup(NAMES, rule_id).map(|s| s.to_string());
            let explanation = lookup(EXPLANATIONS, rule_id).map(|s| s.to_string());
            let remediation = lookup(REMEDIATIONS, rule_id).map(|s| s.to_string());
            let snippet = if context.len() > 200 { &context[..200] } else { &context };
            let matched = if mtext.len() > 200 { &mtext[..200] } else { mtext };

            findings.push(Finding {
                id: rule_id.clone(),
                category,
                pattern,
                severity: severity_for(rule_id, conf),
                confidence: round2(conf),
                location: Location {
                    file: path.to_string(),
                    start_line,
                    end_line: Some(start_line),
                },
                finding: Some(matched.to_string()),
                explanation: explanation.clone(),
                remediation,
                code_snippet: Some(snippet.to_string()),
                intent: None,
                tags: Vec::new(),
            });
        }
    }
    findings
}

/// Severity mapping mirrors the Python `analyze()` convention: HIGH if
/// confidence >= 0.8, MEDIUM if >= 0.5, else LOW. (Upstream uses per-rule
/// severity in each module's analyze(); this is the dominant branch.)
fn severity_for(_rule_id: &str, conf: f64) -> String {
    if conf >= 0.8 {
        "HIGH".to_string()
    } else if conf >= 0.5 {
        "MEDIUM".to_string()
    } else {
        "LOW".to_string()
    }
}

fn round2(x: f64) -> f64 {
    (x * 100.0).round() / 100.0
}

fn extract_context(content: &str, match_start: usize) -> String {
    let window = 3;
    let lines: Vec<&str> = content.split_inclusive('\n').collect();
    let match_line = content[..match_start].matches('\n').count();
    let start = match_line.saturating_sub(window);
    let end = (match_line + window + 1).min(lines.len());
    let ctx: String = lines[start..end].concat();
    if ctx.len() > 400 { ctx[..400].to_string() } else { ctx }
}

/// Recursively collect files under a path (dir) or a single file.
pub fn collect_files(root: &str) -> Vec<String> {
    let mut out = Vec::new();
    let p = std::path::Path::new(root);
    if p.is_dir() {
        let mut stack = vec![p.to_path_buf()];
        while let Some(dir) = stack.pop() {
            if let Ok(entries) = std::fs::read_dir(&dir) {
                for e in entries.flatten() {
                    let path = e.path();
                    if path.is_dir() {
                        stack.push(path);
                    } else {
                        out.push(path.to_string_lossy().to_string());
                    }
                }
            }
        }
        out.sort();
    } else if p.is_file() {
        out.push(root.to_string());
    }
    out
}

/// Scan a list of paths (files or dirs), returning all findings + a summary.
pub fn scan_paths(paths: &[String]) -> (Vec<Finding>, ScanSummary) {
    let mut all = Vec::new();
    let mut files_scanned = 0usize;
    let mut files_skipped = 0usize;
    for root in paths {
        for file in collect_files(root) {
            // skip binary by extension quickly
            if BINARY_EXTS.iter().any(|e| file.to_lowercase().ends_with(e)) {
                files_skipped += 1;
                continue;
            }
            match std::fs::read_to_string(&file) {
                Ok(content) => {
                    if is_binary_file(&file, &content) {
                        files_skipped += 1;
                        continue;
                    }
                    files_scanned += 1;
                    all.extend(scan_file(&file, &content));
                }
                Err(_) => {
                    files_skipped += 1;
                }
            }
        }
    }
    let mut by_sev: HashMap<String, usize> = HashMap::new();
    for f in &all {
        *by_sev.entry(f.severity.clone()).or_insert(0) += 1;
    }
    let summary = ScanSummary {
        files_scanned,
        files_skipped,
        findings: all.len(),
        by_severity: by_sev,
    };
    (all, summary)
}

#[derive(Debug, serde::Serialize)]
pub struct ScanSummary {
    pub files_scanned: usize,
    pub files_skipped: usize,
    pub findings: usize,
    pub by_severity: HashMap<String, usize>,
}
