/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function apply_event_js(a: number, b: number, c: number, d: number): Array;
export function channel_ledger_js(a: number, b: number): Array;
export function estimate_order_total_js(a: number, b: number, c: number): Array;
export function fsm_graph_report_js(): Array;
export function geo_bearing_js(a: number, b: number, c: number, d: number): Array;
export function geo_eta_js(a: number, b: number, c: number): Array;
export function geo_haversine_js(a: number, b: number, c: number, d: number): Array;
export function geo_is_arriving_js(a: number, b: number): Array;
export function geo_is_out_of_order_js(a: number, b: number): Array;
export function geo_lerp_js(a: number, b: number, c: number, d: number, e: number): Array;
export function geo_point_in_polygon_js(a: number, b: number, c: number, d: number): Array;
export function geo_progress_flat_js(a: number, b: number, c: number, d: number): Array;
export function geo_progress_js(a: number, b: number, c: number, d: number): Array;
export function geo_should_snap_js(a: number, b: number, c: number, d: number, e: number): Array;
export function place_order_js(a: number, b: number, c: number, d: number, e: number, f: number): Array;
export function reduce_anomalies_js(a: number, b: number): Array;
export function spectral_algebraic_connectivity_js(a: number, b: number): Array;
export function spectral_classify_drift_js(a: number, b: number): Array;
export function spectral_eigenvalues_js(a: number, b: number): Array;
export function spectral_flat_js(a: number, b: number): Array;
export function spectral_gap_js(a: number, b: number): Array;
export function spectral_radius_js(a: number, b: number): Array;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __externref_table_dealloc(a: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
