import { loadEnv } from '@deliveryos/config';
import { createSessionPool } from '@deliveryos/db';
loadEnv();
const pool = createSessionPool();
const r = await pool.query(`SELECT table_schema, table_name FROM information_schema.tables WHERE table_name = 'users' ORDER BY table_schema`);
console.log('Users tables:');
r.rows.forEach(row => console.log(`  ${row.table_schema}.${row.table_name}`));
const r2 = await pool.query(`SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' ORDER BY ordinal_position`);
console.log('\nPublic users columns:');
r2.rows.forEach(row => console.log(`  ${row.column_name}`));
await pool.end();
