import { loadEnv } from '@deliveryos/config';
import { createSessionPool } from '@deliveryos/db';
loadEnv();
const pool = createSessionPool();
const r = await pool.query(`SELECT column_name FROM information_schema.columns WHERE table_name = 'telegram_connect_tokens' ORDER BY ordinal_position`);
console.log('telegram_connect_tokens columns:');
r.rows.forEach(row => console.log(`  ${row.column_name}`));
const r2 = await pool.query(`SELECT column_name FROM information_schema.columns WHERE table_name = 'owner_notification_targets' ORDER BY ordinal_position`);
console.log('\nowner_notification_targets columns:');
r2.rows.forEach(row => console.log(`  ${row.column_name}`));
await pool.end();
