-- ============================================================================
-- STAGED C2 READ-GATE — for the CLAIM PHASE, not P6-3.
-- ============================================================================
-- Re-versions the two LIVE public-menu functions so a CLAIMED shadow whose products
-- are still source='place' / allergens_confirmed=false never surfaces AI-inferred
-- allergens (operator decision #2 / council C2, POST-claim layer).
--
-- WHY DEFERRED OUT OF P6-3: pre-claim, a shadow is status='closed' and is NEVER served
-- by read_public_menu/all_locales (their WHERE requires status IN ('active','open') OR
-- published_at IS NOT NULL). P6-3's pre-claim allergen safety is fully covered by TWO
-- PROVEN layers: (1) the WRITE-strip in provisioning.ts (bom[].allergens nulled at INSERT),
-- (2) read_preview_menu's `attributes - 'bom'` (migration 070, proven). This re-version is a
-- ~150-line hot-path function whose blast radius (every real tenant's menu) demands a proof
-- against the FULL menu schema — do it on staging in the claim phase, not blind here.
--
-- SOURCES VERIFIED (2026-06-28): read_public_menu latest body = 1790000000065 (lines 21-175);
-- read_public_menu_all_locales latest body = 1790000000035 (lines 14-70) — NOT 065/064 (they
-- leave all_locales untouched). all_locales is LANGUAGE plpgsql, NOT SECURITY DEFINER (kept as-is).
-- The ONLY change vs the verbatim bodies: each `'attributes', p.attributes` →
--   'attributes', CASE WHEN p.source='place' AND p.allergens_confirmed=false THEN p.attributes - 'bom' ELSE p.attributes END
-- Before placing: re-diff against the then-current bodies (a later migration may re-version them).
-- ============================================================================
-- [read-gate SQL — the two CREATE OR REPLACE FUNCTION bodies — assembled from the verified
--  035/065 sources at claim-phase build time, after re-diffing against the live definitions.]
