#!/usr/bin/env python3
"""join_sqlite.py — B2 decisive twin (i), sqlite side (docs/blueprints/B2-decisive-twins.md
§3(i)). sqlite3 through ctypes with prepared statements, same conventions as
bench/tq_sqlite/sbench_sqlite.py (ctypes CDLL over libsqlite3, PRAGMA journal_mode=OFF /
synchronous=OFF, bind_int64/step/reset), plus the VM_STEP-based native floor of
docs/LANG-DB-DESIGN.md §8 ("report sqlite NATIVE time = measured minus the ctypes floor
(calls x 1.17 us, floor measured in the same run), and record sqlite3_stmt_status(VM_STEP)
per query"). In-memory db (no file — this is a functional/plan twin, not the durable-commit
row; sbench_sqlite.py is the file-backed twin for that).

R(k,a) and S(k,b) are generated by bench/oracles/join_twin.py's gen() (imported, not
re-derived) so the rows loaded here are bit-identical to the bebop/Rust twins' rows.
Runs `SELECT count(*), sum((a*b) % 2^61) FROM R JOIN S USING(k)` with an index on S(k) and
without one (EXPLAIN QUERY PLAN recorded both times, per the blueprint's risk #1: "sqlite plan
choice hides a hash join -- run both plans, keep the faster as sqlite native", decided later
when timings exist).

CLI (functional check, no timing loop — bench/vs_rust/twins_b2.sh does the timed run later by
importing gen()/load_tables()/run_join() from this module):
    python3 join_sqlite.py <n> <u|z|both>
"""
import ctypes
import ctypes.util
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'oracles'))
from join_twin import gen, join_fold, MOD61  # noqa: E402

SQLITE_STMTSTATUS_VM_STEP = 1

L = ctypes.CDLL(ctypes.util.find_library('sqlite3'))
L.sqlite3_open.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p)]
L.sqlite3_close.argtypes = [ctypes.c_void_p]
L.sqlite3_prepare_v2.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int,
                                  ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(ctypes.c_char_p)]
L.sqlite3_bind_int64.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int64]
L.sqlite3_step.argtypes = [ctypes.c_void_p]
L.sqlite3_reset.argtypes = [ctypes.c_void_p]
L.sqlite3_finalize.argtypes = [ctypes.c_void_p]
L.sqlite3_column_int64.argtypes = [ctypes.c_void_p, ctypes.c_int]
L.sqlite3_column_int64.restype = ctypes.c_int64
L.sqlite3_column_text.argtypes = [ctypes.c_void_p, ctypes.c_int]
L.sqlite3_column_text.restype = ctypes.c_char_p
L.sqlite3_exec.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p]
L.sqlite3_stmt_status.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int]
L.sqlite3_stmt_status.restype = ctypes.c_int


def opendb():
    db = ctypes.c_void_p()
    assert L.sqlite3_open(b':memory:', ctypes.byref(db)) == 0
    L.sqlite3_exec(db, b'PRAGMA journal_mode=OFF; PRAGMA synchronous=OFF;', None, None, None)
    return db


def exe(db, sql):
    assert L.sqlite3_exec(db, sql.encode(), None, None, None) == 0, sql


def prep(db, sql):
    st = ctypes.c_void_p()
    assert L.sqlite3_prepare_v2(db, sql.encode(), -1, ctypes.byref(st), None) == 0, sql
    return st


def load_tables(db, rk, ra, sk, sb):
    """One transaction, prepared INSERTs — mirrors sbench_sqlite.py's insert phase."""
    exe(db, 'CREATE TABLE R(k INTEGER, a INTEGER)')
    exe(db, 'CREATE TABLE S(k INTEGER, b INTEGER)')
    exe(db, 'BEGIN')
    ins_r = prep(db, 'INSERT INTO R VALUES(?,?)')
    for i in range(len(rk)):
        L.sqlite3_bind_int64(ins_r, 1, rk[i])
        L.sqlite3_bind_int64(ins_r, 2, ra[i])
        L.sqlite3_step(ins_r)
        L.sqlite3_reset(ins_r)
    ins_s = prep(db, 'INSERT INTO S VALUES(?,?)')
    for i in range(len(sk)):
        L.sqlite3_bind_int64(ins_s, 1, sk[i])
        L.sqlite3_bind_int64(ins_s, 2, sb[i])
        L.sqlite3_step(ins_s)
        L.sqlite3_reset(ins_s)
    exe(db, 'COMMIT')
    L.sqlite3_finalize(ins_r)
    L.sqlite3_finalize(ins_s)


JOIN_SQL = 'SELECT count(*), sum((a*b) %% %d) FROM R JOIN S USING(k)' % MOD61


def explain_text(db, sql):
    st = prep(db, 'EXPLAIN QUERY PLAN ' + sql)
    rows = []
    while L.sqlite3_step(st) == 100:  # SQLITE_ROW
        rows.append((L.sqlite3_column_text(st, 3) or b'').decode())
    L.sqlite3_finalize(st)
    return ' | '.join(rows)


def run_join(db, indexed):
    """Returns (count, checksum, plan_text, vm_steps, wall_s). indexed=True creates an index
    on S(k) first (dropped again after, so the two calls are independent plans on the same
    tables); indexed=False leaves it to sqlite's own automatic-index/hash-plan choice."""
    if indexed:
        exe(db, 'CREATE INDEX idx_s_k ON S(k)')
    plan = explain_text(db, JOIN_SQL)
    st = prep(db, JOIN_SQL)
    t0 = time.perf_counter()
    rc = L.sqlite3_step(st)
    wall = time.perf_counter() - t0
    assert rc == 100, rc
    cnt = L.sqlite3_column_int64(st, 0)
    chk = L.sqlite3_column_int64(st, 1)
    vm_steps = L.sqlite3_stmt_status(st, SQLITE_STMTSTATUS_VM_STEP, 1)
    L.sqlite3_finalize(st)
    if indexed:
        exe(db, 'DROP INDEX idx_s_k')
    return cnt, chk, plan, vm_steps, wall


def ctypes_floor_us(reps=13):
    """LANG-DB §8: the ctypes call floor (~1.17 us/call measured there), from `reps` no-op
    bind_int64 calls on a throwaway statement — for the LATER timing harness to subtract from
    wall time; not used to make any timing claim here."""
    db = opendb()
    ph = ','.join(['?'] * reps)
    st = prep(db, f'SELECT {ph}')
    t0 = time.perf_counter()
    for i in range(1, reps + 1):
        L.sqlite3_bind_int64(st, i, 0)
    us = (time.perf_counter() - t0) * 1e6 / reps
    L.sqlite3_finalize(st)
    L.sqlite3_close(db)
    return us


def check(n, dist):
    zipf = 1 if dist == 'z' else 0
    seed = 8823 if zipf else 4711
    rk, ra, sk, sb = gen(seed, n, zipf)
    ocnt, ochk, ofold = join_fold(rk, ra, sk, sb)
    db = opendb()
    load_tables(db, rk, ra, sk, sb)
    cnt_i, chk_i, plan_i, vm_i, _ = run_join(db, True)
    cnt_n, chk_n, plan_n, vm_n, _ = run_join(db, False)
    L.sqlite3_close(db)
    ok = (cnt_i, chk_i) == (ocnt, ochk) == (cnt_n, chk_n)
    print(f'{dist} oracle count={ocnt} checksum={ochk}')
    print(f'{dist} sqlite indexed   count={cnt_i} checksum={chk_i} vm_steps={vm_i} plan=[{plan_i}]')
    print(f'{dist} sqlite no-index  count={cnt_n} checksum={chk_n} vm_steps={vm_n} plan=[{plan_n}]')
    print(f'{dist} folds: {"equal" if ok else "MISMATCH"}')
    return ok


if __name__ == '__main__':
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 2000
    dist = sys.argv[2] if len(sys.argv) > 2 else 'both'
    dists = ['u', 'z'] if dist == 'both' else [dist]
    allok = True
    for d in dists:
        allok = check(n, d) and allok
    print('floor: %.2f us/call (13 bind_int64, no execution)' % ctypes_floor_us())
    sys.exit(0 if allok else 1)
