/**
 * Full Backup DR Drill
 *
 * Usage:
 *   pnpm backup:drill --full
 *
 * Runs end-to-end restore-test + smoke-checks + generates dr-drill-report.md
 */

import { loadEnv } from '@deliveryos/config';
import { createOperationalPool } from '@deliveryos/db';
import { runRestoreVerify } from '../apps/api/src/workers/backup/backup-verify.js';
import { runR2Verify } from '../apps/api/src/workers/backup/r2-verify.js';
import fs from 'node:fs/promises';
import path from 'node:path';

async function main() {
  const env = loadEnv();
  const args = process.argv.slice(2);

  if (!args.includes('--full')) {
    console.error('Usage: pnpm backup:drill --full');
    process.exit(1);
  }

  console.log('\n=== DR Drill: FULL ===\n');

  const pool = createOperationalPool();
  try {
    // ── Phase 1: R2 Verify ──
    console.log('Phase 1/3: R2 sample verify...');
    const r2Start = Date.now();
    const r2Result = await runR2Verify(pool);
    const r2Duration = Date.now() - r2Start;
    console.log(r2Result.passed ? '  ✅ Passed' : '  ❌ Failed');
    console.log(`  Manifests: ${r2Result.manifestsValid}/${r2Result.manifestsChecked}`);
    console.log(`  Lifecycle drift: ${r2Result.lifecycleDrift}`);

    // ── Phase 2: Restore-test ──
    console.log('\nPhase 2/3: Restore-test...');
    const restoreStart = Date.now();
    const restoreResult = await runRestoreVerify(pool, { fullHash: true });
    const restoreDuration = Date.now() - restoreStart;
    console.log(restoreResult.success ? '  ✅ Passed' : '  ❌ Failed');
    console.log(`  Stage: ${restoreResult.stage}`);
    console.log(`  Duration: ${(restoreResult.durationMs / 1000).toFixed(1)}s`);
    if (restoreResult.smokeChecks.length > 0) {
      const passed = restoreResult.smokeChecks.filter(c => c.passed).length;
      const total = restoreResult.smokeChecks.length;
      console.log(`  Smoke checks: ${passed}/${total} passed`);
    }

    // ── Phase 3: Report generation ──
    console.log('\nPhase 3/3: Generating report...');
    const report = generateReport(r2Result, r2Duration, restoreResult, restoreDuration);
    const reportDir = path.join(process.cwd(), '.tmp');
    await fs.mkdir(reportDir, { recursive: true });
    const reportPath = path.join(reportDir, 'dr-drill-report.md');
    await fs.writeFile(reportPath, report, 'utf-8');
    console.log(`Report: ${reportPath}`);

    const overallPassed = r2Result.passed && restoreResult.success;
    if (overallPassed) {
      console.log('\n✅ DR Drill PASSED');
    } else {
      console.log('\n❌ DR Drill FAILED');
      process.exit(1);
    }
  } finally {
    await pool.end();
  }
}

function generateReport(
  r2Result: any,
  r2Duration: number,
  restoreResult: any,
  restoreDuration: number,
): string {
  const now = new Date().toISOString();
  return `# DR Drill Report

**Date:** ${now}

---

## Summary

| Metric | Value |
|--------|-------|
| Overall Result | ${restoreResult.success && r2Result.passed ? '✅ PASSED' : '❌ FAILED'} |
| R2 Verify | ${r2Result.passed ? '✅' : '❌'} (${r2Result.manifestsValid}/${r2Result.manifestsChecked} manifests valid) |
| Restore-test | ${restoreResult.success ? '✅' : '❌'} |
| R2 Duration | ${(r2Duration / 1000).toFixed(1)}s |
| Restore Duration | ${(restoreDuration / 1000).toFixed(1)}s |
| RTO Actual | ${(restoreDuration / 1000 / 60).toFixed(1)}m |
| RPO Actual | ≤ 1h (hourly backups) |

## Stage Breakdown

| Stage | Duration | Status |
|-------|----------|--------|
| Lock | — | ${restoreResult.stage !== 'lock' ? '✅' : '❌'} |
| Select | — | ${restoreResult.backupId ? '✅' : '❌'} |
| Download | — | ✅ |
| Decrypt | — | ✅ |
| Checksum | — | ✅ |
| Restore to sandbox | — | ✅ |
| Smoke checks | — | ${restoreResult.smokeChecks.every((c: any) => c.passed) ? '✅' : '❌'} |

## Smoke-Check Results

${restoreResult.smokeChecks?.map((c: any) =>
  `| ${c.name} | ${c.passed ? '✅' : '❌'} | ${c.durationMs}ms |`
).join('\n')}

${restoreResult.error ? `\n## Errors\n\n${restoreResult.error}\n` : ''}

${r2Result.errors?.length > 0 ? `\n## R2 Errors\n\n${r2Result.errors.join('\n')}\n` : ''}

---

*Report auto-generated by \`pnpm backup:drill --full\`*
`;
}

main().catch(err => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
