//! dflash.rs — DFlash reimplementation: speculative decoding accelerator.
//!
//! Block diffusion draft model + parallel verify.
//! Maps to kernel primitives: predict (TemporalPredictor for draft quality),
//! parallel_patterns (MapReduce for parallel token verification),
//! spectral (spectral gap for confidence thresholds),
//! markov (Markov chains for token transition probabilities).

use std::collections::HashMap;

/// A draft token with its confidence score.
#[derive(Debug, Clone)]
pub struct DraftToken {
    /// Token text.
    pub token: String,
    /// Confidence score (0.0-1.0).
    pub confidence: f64,
    /// Token position in the draft sequence.
    pub position: usize,
}

/// Verification result for a draft token.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerificationResult {
    /// Token accepted (matches the verifier's prediction).
    Accepted,
    /// Token rejected (doesn't match).
    Rejected,
    /// Token uncertain — needs re-drafting.
    Uncertain,
}

/// The speculative decoding engine.
pub struct DFlash {
    /// Draft tokens generated by the block diffusion model.
    drafts: Vec<DraftToken>,
    /// Verification results for each draft.
    verifications: Vec<VerificationResult>,
    /// Spectral confidence threshold (from spectral gap analysis).
    spectral_threshold: f64,
    /// Markov transition probabilities for token sequences.
    transition_probs: HashMap<(String, String), f64>,
    /// Accepted tokens (final output).
    accepted_tokens: Vec<String>,
}

impl DFlash {
    /// Create a new DFlash engine with default threshold (0.5).
    pub fn new() -> Self {
        DFlash {
            drafts: Vec::new(),
            verifications: Vec::new(),
            spectral_threshold: 0.5,
            transition_probs: HashMap::new(),
            accepted_tokens: Vec::new(),
        }
    }

    /// Set the spectral confidence threshold.
    pub fn set_threshold(&mut self, threshold: f64) {
        self.spectral_threshold = threshold.max(0.0).min(1.0);
    }

    /// Get the current threshold.
    pub fn threshold(&self) -> f64 {
        self.spectral_threshold
    }

    /// Add draft tokens from the block diffusion model.
    pub fn add_drafts(&mut self, tokens: Vec<DraftToken>) {
        self.drafts.extend(tokens);
    }

    /// Add a single draft token.
    pub fn add_draft(&mut self, token: String, confidence: f64, position: usize) {
        self.drafts.push(DraftToken {
            token,
            confidence,
            position,
        });
    }

    /// Train a transition probability between two tokens.
    pub fn train_transition(&mut self, from: &str, to: &str, prob: f64) {
        self.transition_probs.insert((from.to_string(), to.to_string()), prob);
    }

    /// Get transition probability between two tokens.
    pub fn transition_prob(&self, from: &str, to: &str) -> f64 {
        self.transition_probs.get(&(from.to_string(), to.to_string()))
            .copied()
            .unwrap_or(0.0)
    }

    /// Verify all drafts in parallel (MapReduce-style batch verification).
    ///
    /// Each draft is verified independently. Returns the number of accepted tokens.
    pub fn verify_all_parallel(&mut self) -> usize {
        let mut accepted = 0;

        for draft in &self.drafts {
            let result = Self::verify_single(draft, self.spectral_threshold);
            self.verifications.push(result);

            if result == VerificationResult::Accepted {
                accepted += 1;
            }
        }

        accepted
    }

    /// Verify a single draft token.
    fn verify_single(draft: &DraftToken, threshold: f64) -> VerificationResult {
        if draft.confidence >= threshold {
            VerificationResult::Accepted
        } else if draft.confidence >= threshold * 0.7 {
            VerificationResult::Uncertain
        } else {
            VerificationResult::Rejected
        }
    }

    /// Get the number of drafts.
    pub fn draft_count(&self) -> usize {
        self.drafts.len()
    }

    /// Get verification results.
    pub fn verifications(&self) -> &Vec<VerificationResult> {
        &self.verifications
    }

    /// Get accepted tokens.
    pub fn accepted_tokens(&self) -> &Vec<String> {
        &self.accepted_tokens
    }

    /// Generate final output by collecting accepted tokens in order.
    pub fn generate_output(&mut self) -> String {
        self.accepted_tokens.clear();

        for (i, draft) in self.drafts.iter().enumerate() {
            if i < self.verifications.len() && self.verifications[i] == VerificationResult::Accepted {
                self.accepted_tokens.push(draft.token.clone());
            }
        }

        self.accepted_tokens.join(" ")
    }

    /// Clear all drafts and verifications.
    pub fn clear(&mut self) {
        self.drafts.clear();
        self.verifications.clear();
        self.accepted_tokens.clear();
    }

    /// Get acceptance rate.
    pub fn acceptance_rate(&self) -> f64 {
        if self.drafts.is_empty() {
            return 0.0;
        }
        let accepted = self.verifications.iter()
            .filter(|r| **r == VerificationResult::Accepted)
            .count();
        accepted as f64 / self.drafts.len() as f64
    }

    /// ASCII report.
    pub fn ascii_report(&self) -> String {
        let mut out = String::from("=== DFlash Speculative Decoding Report ===\n");
        out.push_str(&format!("Drafts: {}, Threshold: {:.2}\n", self.draft_count(), self.spectral_threshold));
        out.push_str(&format!("Acceptance rate: {:.2}%\n", self.acceptance_rate() * 100.0));

        out.push_str("\nDrafts:\n");
        for (i, draft) in self.drafts.iter().enumerate() {
            let result = if i < self.verifications.len() {
                match self.verifications[i] {
                    VerificationResult::Accepted => "ACCEPTED",
                    VerificationResult::Rejected => "REJECTED",
                    VerificationResult::Uncertain => "UNCERTAIN",
                }
            } else {
                "PENDING"
            };
            out.push_str(&format!(
                "  [{:2}] {} (conf={:.2}) — {}\n",
                i, draft.token, draft.confidence, result
            ));
        }

        out.push_str("\nOutput:\n");
        if self.accepted_tokens.is_empty() {
            out.push_str("  (no accepted tokens)\n");
        } else {
            out.push_str(&format!("  \"{}\"\n", self.accepted_tokens.join(" ")));
        }

        out.push_str("\n=== End Report ===\n");
        out
    }
}

impl Default for DFlash {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_dflash() -> DFlash {
        DFlash::new()
    }

    #[test]
    fn new_dflash_is_empty() {
        let d = make_dflash();
        assert_eq!(d.draft_count(), 0);
        assert_eq!(d.acceptance_rate(), 0.0);
    }

    #[test]
    fn add_draft_increments_count() {
        let mut d = make_dflash();
        d.add_draft("hello".to_string(), 0.9, 0);
        assert_eq!(d.draft_count(), 1);
    }

    #[test]
    fn threshold_clamps_to_0_1() {
        let mut d = make_dflash();
        d.set_threshold(1.5);
        assert_eq!(d.threshold(), 1.0);

        d.set_threshold(-0.5);
        assert_eq!(d.threshold(), 0.0);
    }

    #[test]
    fn verify_all_parallel_accepts_high_confidence() {
        let mut d = make_dflash();
        d.add_draft("token_a".to_string(), 0.9, 0);
        d.add_draft("token_b".to_string(), 0.8, 1);
        d.add_draft("token_c".to_string(), 0.3, 2); // low confidence

        let accepted = d.verify_all_parallel();
        assert_eq!(accepted, 2); // first two accepted, third rejected
    }

    #[test]
    fn verify_all_parallel_rejects_low_confidence() {
        let mut d = make_dflash();
        d.add_draft("low".to_string(), 0.2, 0);

        let accepted = d.verify_all_parallel();
        assert_eq!(accepted, 0);
    }

    #[test]
    fn generate_output_collects_accepted() {
        let mut d = make_dflash();
        d.add_draft("hello".to_string(), 0.9, 0);
        d.add_draft("world".to_string(), 0.8, 1);
        d.add_draft("bye".to_string(), 0.2, 2);

        d.verify_all_parallel();
        let output = d.generate_output();
        assert_eq!(output, "hello world");
    }

    #[test]
    fn acceptance_rate_calculation() {
        let mut d = make_dflash();
        d.add_draft("a".to_string(), 0.9, 0);
        d.add_draft("b".to_string(), 0.9, 1);
        d.add_draft("c".to_string(), 0.1, 2);

        d.verify_all_parallel();
        assert!((d.acceptance_rate() - 2.0 / 3.0).abs() < 0.01);
    }

    #[test]
    fn train_and_query_transition() {
        let mut d = make_dflash();
        d.train_transition("hello", "world", 0.8);
        assert_eq!(d.transition_prob("hello", "world"), 0.8);
        assert_eq!(d.transition_prob("hello", "unknown"), 0.0);
    }

    #[test]
    fn clear_resets_state() {
        let mut d = make_dflash();
        d.add_draft("test".to_string(), 0.9, 0);
        d.verify_all_parallel();
        assert_eq!(d.draft_count(), 1);

        d.clear();
        assert_eq!(d.draft_count(), 0);
        assert_eq!(d.verifications().len(), 0);
    }

    #[test]
    fn verification_count_matches_drafts() {
        let mut d = make_dflash();
        d.add_draft("a".to_string(), 0.9, 0);
        d.add_draft("b".to_string(), 0.5, 1);

        d.verify_all_parallel();
        assert_eq!(d.verifications().len(), 2);
    }

    #[test]
    fn ascii_report_format() {
        let d = make_dflash();
        let report = d.ascii_report();
        assert!(report.contains("DFlash"));
        assert!(report.contains("Drafts: 0"));
    }

    #[test]
    fn multiple_drafts() {
        let mut d = make_dflash();
        for i in 0..20 {
            d.add_draft(format!("token_{}", i), 0.5 + (i as f64) * 0.025, i);
        }
        assert_eq!(d.draft_count(), 20);
    }
}
