// GENERATED by eqc-rs — do not hand-edit.
// Source equation (BLUEPRINT-P-A §3.1, A2):
//   ema_next = prev + alpha * (sample - prev)
// This file is the committed, hand-inspectable artifact emitted by
// `tools/eqc-rs/src/bin/gen_kernel_organs.rs` at authoring time. The emitted
// Rust has ZERO runtime dependency on eqc-rs.

/// GENERATED by eqc-rs from: ema_next
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn ema_next_f64(prev: f64, sample: f64, alpha: f64) -> f64 {
    // RED stub — returns 0.0 so the parity test fails until the real generated
    // body is committed (GREEN phase). Do NOT hand-edit the math; regenerate.
    0.0
}
