// GENERATED by eqc-rs — do not hand-edit.
// Source equation (BLUEPRINT-P-A §3.1, A2):
//   ema_next = prev + alpha * (sample - prev)
// This file is the committed, hand-inspectable artifact emitted by
// `tools/eqc-rs/src/bin/gen_kernel_organs.rs` at authoring time. The emitted
// Rust has ZERO runtime dependency on eqc-rs.

/// GENERATED by eqc-rs from: ema_next
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn ema_next_f64(prev: f64, sample: f64, alpha: f64) -> f64 {
    (prev + (alpha * (sample + (-1.0f64 * prev))))
}

// ── A3 money-law shadow organs (BLUEPRINT-P-A §3.3) ─────────────────────────
// GENERATED by eqc-rs from: apply_tax_exclusive / apply_tax_inclusive via
// `emit_int_checked_rust`. Integer-exact mirrors of `apply_tax`'s two legs
// (kernel/src/money.rs). These are SHADOW organs: applied verbatim from the
// equation-of-truth; the authority flip (callers switching to them) is W4-L1,
// operator docket R-4 — NOT done here.
//
// RED stub (return Ok(0)) is replaced by the real generated body in the GREEN
// commit; the parity test (money.rs) asserts exact-integer equality against the
// hand-written `apply_tax`, and is RED against this stub.

/// GENERATED by eqc-rs from: apply_tax_exclusive
/// Integer-exact variant — raw i64 (minor units), i128 arithmetic, every
/// step checked. Returns Result<i64, &'static str> (Err on overflow/div-by-zero).
#[inline(always)]
pub fn apply_tax_exclusive_int(sub: i64, rate_micro: i64) -> Result<i64, &'static str> {
    use std::convert::TryFrom;
    i64::try_from({
        let b = (1000000i128);
        if b == 0i128 {
            return Err("division by zero in DivHalfUp");
        }
        (((sub as i128)
            .checked_mul((rate_micro as i128))
            .ok_or("overflow in Prod")?)
            + b / 2)
            / b
    })
    .map_err(|_| "overflow: result exceeds i64")
}

/// GENERATED by eqc-rs from: apply_tax_inclusive
/// Integer-exact variant — raw i64 (minor units), i128 arithmetic, every
/// step checked. Returns Result<i64, &'static str> (Err on overflow/div-by-zero).
#[inline(always)]
pub fn apply_tax_inclusive_int(sub: i64, rate_micro: i64) -> Result<i64, &'static str> {
    use std::convert::TryFrom;
    i64::try_from(
        ((sub as i128)
            .checked_add(
                ((-1i128)
                    .checked_mul({
                        let b = ((1000000i128)
                            .checked_add((rate_micro as i128))
                            .ok_or("overflow in Sum")?);
                        if b == 0i128 {
                            return Err("division by zero in DivHalfUp");
                        }
                        (((sub as i128)
                            .checked_mul((1000000i128))
                            .ok_or("overflow in Prod")?)
                            + b / 2)
                            / b
                    })
                    .ok_or("overflow in Prod")?),
            )
            .ok_or("overflow in Sum")?),
    )
    .map_err(|_| "overflow: result exceeds i64")
}
