//! modular.rs — the modular group PSL(2,Z) and its Möbius action.
//!
//! Item #6 of screenshot-batch-2. The post showed PSL(2,Z) acting on a
//! coordinate ring (Legendrian-knot monodromy); the *reusable* primitive is
//! the modular group itself: fractional-linear (Möbius) transformations
//! z ↦ (az+b)/(cz+d) with ad−bc = 1, generated by S: z ↦ −1/z and T: z ↦ z+1.
//!
//! This is the purest "geometry over algebra" organ in the kernel: a Möbius
//! transform is a composition of translations, rotations and inversions — the
//! same substrate as `trig::Phase`, lifted to the upper half-plane.

use crate::spectral::Complex;

/// An integer Möbius transformation (PSL(2,Z) matrix, det = ad−bc = 1).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Mobius {
    pub a: i64,
    pub b: i64,
    pub c: i64,
    pub d: i64,
}

impl Mobius {
    /// The identity z ↦ z.
    pub const fn identity() -> Self {
        Self { a: 1, b: 0, c: 0, d: 1 }
    }

    /// Generator S: z ↦ −1/z.
    pub const fn s() -> Self {
        Self { a: 0, b: -1, c: 1, d: 0 }
    }

    /// Generator T: z ↦ z+1.
    pub const fn t() -> Self {
        Self { a: 1, b: 1, c: 0, d: 1 }
    }

    /// Determinant ad − bc (must be 1 for PSL(2,Z)).
    pub const fn det(self) -> i64 {
        self.a * self.d - self.b * self.c
    }

    /// Apply the transformation to a complex point.
    /// Fail-closed: if `z` is (near) a pole of the transform (denominator
    /// ~0), returns `z` unchanged instead of propagating NaN/Inf.
    pub fn apply(self, z: Complex) -> Complex {
        let num = Complex::new(
            (self.a as f64) * z.re + (self.b as f64),
            (self.a as f64) * z.im,
        );
        let den = Complex::new(
            (self.c as f64) * z.re + (self.d as f64),
            (self.c as f64) * z.im,
        );
        let dn = den.re * den.re + den.im * den.im;
        if dn < 1e-15 {
            return z; // pole (measure-zero): fail-closed, no NaN propagation
        }
        num.div(den)
    }

    /// Compose `self ∘ other` (apply `other` first).
    pub fn compose(self, other: Mobius) -> Mobius {
        Mobius {
            a: self.a * other.a + self.b * other.c,
            b: self.a * other.b + self.b * other.d,
            c: self.c * other.a + self.d * other.c,
            d: self.c * other.b + self.d * other.d,
        }
    }
}

/// Is `z` in the fundamental domain F = { |z| ≥ 1, |Re(z)| ≤ 1/2 } (upper
/// half-plane Im(z) > 0)?
pub fn in_fundamental_domain(z: Complex) -> bool {
    z.im > 0.0 && z.abs() >= 1.0 - 1e-12 && z.re.abs() <= 0.5 + 1e-12
}

/// Reduce a point to the fundamental domain by iterating S and T.
/// Standard modular reduction: while |z| < 1, apply S; while |Re| > 1/2,
/// apply T^(−round(Re)). Returns the reduced point (and its orbit is the
/// same coset in PSL(2,Z)\H). Bounded to `max_iter` to stay deterministic.
pub fn reduce(z: Complex, max_iter: usize) -> Complex {
    let mut z = z;
    let s = Mobius::s();
    for _ in 0..max_iter {
        // Translate into the strip |Re| ≤ 1/2.
        let shift = z.re.round();
        if shift != 0.0 {
            let t = Mobius {
                a: 1,
                b: -(shift as i64),
                c: 0,
                d: 1,
            };
            z = t.apply(z);
        }
        // Invert if inside the unit circle.
        if z.abs() < 1.0 - 1e-12 {
            z = s.apply(z);
        } else if in_fundamental_domain(z) {
            break;
        } else {
            break; // safety: leave as-is
        }
    }
    z
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn s_squares_to_identity() {
        let z = Complex::new(0.3, 1.5);
        let once = Mobius::s().apply(z);
        let twice = Mobius::s().apply(once);
        // S² = id (as a projective transformation): S(S(z)) == z.
        assert!((twice.re - z.re).abs() < 1e-9);
        assert!((twice.im - z.im).abs() < 1e-9);
    }

    #[test]
    fn t_adds_one() {
        let z = Complex::new(0.3, 1.5);
        let tz = Mobius::t().apply(z);
        assert!((tz.re - (z.re + 1.0)).abs() < 1e-9);
        assert!((tz.im - z.im).abs() < 1e-9);
    }

    #[test]
    fn st_cubed_is_identity() {
        // (ST)³ = id is the defining relation of PSL(2,Z).
        let st = Mobius::s().compose(Mobius::t());
        let st3 = st.compose(st).compose(st);
        assert_eq!(st3.det(), 1);
        let z = Complex::new(0.4, 2.0);
        let r = st3.apply(z);
        assert!((r.re - z.re).abs() < 1e-9, "Re {} vs {}", r.re, z.re);
        assert!((r.im - z.im).abs() < 1e-9, "Im {} vs {}", r.im, z.im);
    }

    #[test]
    fn generators_have_unit_determinant() {
        assert_eq!(Mobius::s().det(), 1);
        assert_eq!(Mobius::t().det(), 1);
        assert_eq!(Mobius::identity().det(), 1);
    }

    #[test]
    fn reduce_lands_in_fundamental_domain() {
        // A point far outside the fundamental domain reduces into F.
        let z = Complex::new(3.7, 0.2);
        let r = reduce(z, 200);
        assert!(in_fundamental_domain(r), "reduced point {r:?} not in F");
    }

    #[test]
    fn fundamental_domain_classifier() {
        assert!(in_fundamental_domain(Complex::new(0.2, 1.0)));
        assert!(in_fundamental_domain(Complex::new(0.0, 2.0)));
        assert!(!in_fundamental_domain(Complex::new(0.9, 1.0))); // Re > 1/2
        assert!(!in_fundamental_domain(Complex::new(0.0, 0.5))); // |z| < 1
        assert!(!in_fundamental_domain(Complex::new(0.0, -1.0))); // lower half-plane
    }
}
