#!/usr/bin/env python3
"""lower.py — T55 SPIKE (operator request 2026-09-04): lower ONE straight-line
function to substrate cells and emit a .bp that runs it both ways.

The function is the op list OPS below (12 binary ops over inputs a,b and two
constants; the same list is the single source of truth for BOTH modes):
  linear   : the ops emitted as `let` chains (inlined into the driver loop,
             plus a called-fn variant) — ordinary stack-machine code.
  substrate: each op = one cell (op, src1, src2); a cell fires when all its
             inputs have fired; one SWEEP drains the activity word LSB-first
             (de Bruijn tzcnt), evaluates the fired cells branch-free
             (multiply-select over the op code), and computes the next
             activity word from the dependents whose inputs are all fired.
             Execution ends at quiescence (activity == 0). Depth = 7 sweeps
             per evaluation for this DAG.
Output: spike.bp (returns ok*1e13 + swok*1e12 + lin_ms*1e6 + sub_ms),
        spike_fold.bp (returns the linear fold, for the Rust twin check),
        spike_twin.rs (same ops, wrapping i64, prints "fold ms").
"""
import sys
N = int(sys.argv[1]) if len(sys.argv) > 1 else 300000
# cells 0..3 = a, b, const 3, const 7; ops: (dst, opcode, src1, src2)
OPN = {'+':0, '-':1, '*':2, '^':3, '&':4, '|':5}
OPS = [(4,'+',0,1),(5,'*',0,2),(6,'^',1,3),(7,'-',4,5),(8,'&',5,6),(9,'|',4,6),
       (10,'*',7,8),(11,'+',9,3),(12,'^',10,11),(13,'-',12,7),(14,'+',13,8),(15,'*',14,2)]
NC = 16; RESULT = 15; INPUTS = {0:'a', 1:'b', 2:'3', 3:'7'}
def name(c): return INPUTS[c] if c in INPUTS else f't{c}'
# --- linear body (both inlined and as fn) ---
lin_lets = '\n'.join(f'  let t{d} = {name(x)} {op} {name(y)};' for d,op,x,y in OPS)
# --- cell tables ---
dep = [0]*NC; inm = [0]*NC
for d,op,x,y in OPS:
    dep[x] |= 1<<d; dep[y] |= 1<<d; inm[d] = (1<<x)|(1<<y)
tab = []
for c in range(NC):
    row = next(((OPN[op],x,y) for d,op,x,y in OPS if d==c), (0,0,0))
    tab += [row[0], row[1], row[2], dep[c], inm[c]]
first_ready = sum(1<<d for d,op,x,y in OPS if inm[d] & ~0b1111 == 0)
depth = 0; lvl = {c:0 for c in INPUTS}
for d,op,x,y in OPS: lvl[d] = max(lvl[x], lvl[y]) + 1; depth = max(depth, lvl[d])
DB = [0,1,48,2,57,49,28,3,61,58,50,42,38,29,17,4,62,55,59,36,53,51,43,22,45,39,33,30,24,18,12,5,63,47,56,27,60,41,37,16,54,35,52,21,44,32,23,11,46,26,40,15,34,20,31,10,25,14,19,9,13,8,7,6]
fill_tab = '\n'.join(f'  let _ = tab[{i}] = {v};' for i,v in enumerate(tab))
fill_db = '\n'.join(f'  let _ = db[{i}] = {v};' for i,v in enumerate(DB))
common = f'''// GENERATED by bench/substrate_spike/lower.py N={N} — do not edit.
// One straight-line fn ({len(OPS)} ops, DAG depth {depth}) in linear mode and on the
// cell substrate (sweep to quiescence). Same op list, same fold.
fn f_lin(a: i64, b: i64) -> i64 {{
{lin_lets}
  t{RESULT}
}}
fn fill_tab(tab: [i64]) -> i64 {{
{fill_tab}
  0
}}
fn fill_db(db: [i64]) -> i64 {{
{fill_db}
  0
}}
// cell op select, branch-free: opcode 0 + 1 - 2 * 3 ^ 4 & 5 |
fn cell_eval(op: i64, x: i64, y: i64) -> i64 {{
  (op == 0) * (x + y) + (op == 1) * (x - y) + (op == 2) * (x * y) + (op == 3) * (x ^ y) + (op == 4) * (x & y) + (op == 5) * (x | y)
}}
// one sweep: drain st[0] (activity) LSB-first, fire cells, mark st[1] (fired),
// collect st[2] (candidates = dependents of fired cells), then next activity =
// candidates whose input mask is covered by fired. tab stride 5: op s1 s2 dep inm.
fn sweep(val: [i64], tab: [i64], st: [i64], db: [i64]) -> i64 {{
  let act = st[0];
  while act != 0 {{
    let lsb = act - (act & (act - 1));
    let i = db[((lsb * 285870213051386505) >> 58) & 63];
    let _ = val[i] = cell_eval(tab[i * 5], val[tab[i * 5 + 1]], val[tab[i * 5 + 2]]);
    let _ = st[1] = st[1] | lsb;
    let _ = st[2] = st[2] | tab[i * 5 + 3];
    let act = act - lsb;
    0
  }};
  let cand = st[2];
  let nxt = 0;
  while cand != 0 {{
    let lsb = cand - (cand & (cand - 1));
    let d = db[((lsb * 285870213051386505) >> 58) & 63];
    let nxt = nxt + ((tab[d * 5 + 4] & (0 - 1 - st[1])) == 0) * lsb;
    let cand = cand - lsb;
    0
  }};
  let _ = st[2] = 0;
  let _ = st[0] = nxt;
  nxt
}}
// linear, inlined into the driver loop (what --substrate would replace)
fn run_lin_inline(n: i64) -> i64 {{
  let acc = 0;
  let k = n;
  while k > 0 {{
    let a = k;
    let b = k * 3 + 1;
{lin_lets.replace(chr(10), chr(10)+'  ')}
    let acc = acc + t{RESULT};
    let k = k - 1;
    0
  }};
  acc
}}
fn run_lin_call(n: i64) -> i64 {{
  let acc = 0;
  let k = n;
  while k > 0 {{
    let acc = acc + f_lin(k, k * 3 + 1);
    let k = k - 1;
    0
  }};
  acc
}}
// substrate: reset inputs + activity, sweep to quiescence, read the result cell.
// sw[0] accumulates the sweep count (expected {depth} per evaluation).
fn run_sub(n: i64, val: [i64], tab: [i64], st: [i64], db: [i64], sw: [i64]) -> i64 {{
  let acc = 0;
  let k = n;
  while k > 0 {{
    let _ = val[0] = k;
    let _ = val[1] = k * 3 + 1;
    let _ = st[0] = {first_ready};
    let _ = st[1] = 15;
    let _ = st[2] = 0;
    while st[0] != 0 {{
      let _ = sweep(val, tab, st, db);
      let _ = sw[0] = sw[0] + 1;
      0
    }};
    let acc = acc + val[{RESULT}];
    let k = k - 1;
    0
  }};
  acc
}}
'''
main_bench = f'''fn main() -> i64 {{
  let val = zeros(16);
  let tab = zeros(80);
  let st = zeros(4);
  let db = zeros(64);
  let sw = zeros(1);
  let _ = fill_tab(tab);
  let _ = fill_db(db);
  let _ = val[2] = 3;
  let _ = val[3] = 7;
  let t0 = clock_ms();
  let r_lin = run_lin_inline({N});
  let t1 = clock_ms();
  let r_call = run_lin_call({N});
  let t2 = clock_ms();
  let r_sub = run_sub({N}, val, tab, st, db, sw);
  let t3 = clock_ms();
  let ok = (r_lin == r_sub) * (r_lin == r_call);
  let swok = (sw[0] == {depth} * {N});
  ok * 10000000000000 + swok * 1000000000000 + (t1 - t0) * 1000000000 + (t2 - t1) * 1000000 + (t3 - t2)
}}
'''
main_fold = f'fn main() -> i64 {{ run_lin_inline({N}) }}\n'
open('spike.bp','w').write(common + main_bench)
open('spike_fold.bp','w').write(common + main_fold)
rs_lets = '\n'.join(f'        let t{d}: i64 = {name(x)}.wrapping_{ {"+":"add","-":"sub","*":"mul"}[op] }({name(y)});' if op in '+-*' else f'        let t{d}: i64 = {name(x)} {op} {name(y)};' for d,op,x,y in OPS)
open('spike_twin.rs','w').write(f'''// GENERATED by lower.py — Rust twin of run_lin_inline (wrapping i64). Prints "fold ms".
use std::hint::black_box;
fn main() {{
    let n: i64 = black_box({N});
    let t0 = std::time::Instant::now();
    let mut acc: i64 = 0;
    let mut k = n;
    while k > 0 {{
        let a: i64 = black_box(k);
        let b: i64 = k.wrapping_mul(3).wrapping_add(1);
{rs_lets.replace('let t2:','let t2c:').replace(' 3.wrapping',' (3i64).wrapping').replace(' 7.wrapping',' (7i64).wrapping')}
        acc = acc.wrapping_add(t{RESULT});
        k -= 1;
    }}
    let ms = t0.elapsed().as_secs_f64() * 1000.0;
    println!("{{}} {{:.3}}", black_box(acc), ms);
}}
''')
print(f'ops={len(OPS)} depth={depth} first_ready={first_ready} N={N}')
