# D11-L (2026-09-05): one-shot split of the old ROADMAP.md into HISTORY.md + TASKS.md;
# afterwards `tools/roadmap_check.sh` regenerates TASKS.md from HISTORY.md headers and
# fails on drift. Usage: python3 tools/split_roadmap.py [--from HISTORY.md]
import re, subprocess, datetime
import sys
src = open(sys.argv[2] if len(sys.argv) > 2 and sys.argv[1] == '--from' else 'ROADMAP.md').read()
lines = src.split('\n')
# ---- TASKS.md: the ledger from the headers ----
hdr = re.findall(r'^\*\*(T\d+(?:-T\d+)?)[ ·.]+([^\n]*)', src, re.M)
seen = {}
for t, rest in hdr:
    if t in seen: continue
    st = ('DONE' if re.search(r'DONE ✓|— DONE\b|DONE \(|— DONE', rest) else 'CORE DONE' if 'CORE DONE' in rest else
          'RE-SCOPED' if 'RE-SCOPED' in rest else 'PARTIAL' if ('PARTIAL' in rest or 'STEP' in rest) else 'TERMINAL' if 'TERMINAL' in rest else 'OPEN')
    title = re.split(r' — | -- ', rest)[0].strip().rstrip('*')
    seen[t] = (st, title[:110])
# known multi-line DONE headers the regex misses (status on the second line)
for t in ['T27','T28','T29','T31','T36','T38','T40']:
    if t in seen and seen[t][0] == 'OPEN': seen[t] = ('DONE', seen[t][1])
if 'T39' in seen: seen['T39'] = ('PARTIAL', seen['T39'][1])
if 'T97' in seen: seen['T97'] = ('DONE', seen['T97'][1])
from collections import Counter
cnt = Counter(s for s, _ in seen.values())
tasks = ['Status: %s CURRENT (generated by tools/split_roadmap.py from the task headers; edit the headers in HISTORY.md / the pulls, not this table)' % datetime.date.today(),
         '', '# TASKS — the ledger', '', '| status | count |', '|---|---|'] + ['| %s | %d |' % (k, v) for k, v in sorted(cnt.items())] + \
        ['', '| id | status | title |', '|---|---|---|'] + ['| %s | %s | %s |' % (t, s, ti.replace('|', '/')) for t, (s, ti) in seen.items()]
open('TASKS.md', 'w').write('\n'.join(tasks) + '\n')
# ---- HISTORY.md: everything after the thesis, verbatim ----
i_goal = lines.index('## Terminal goal') if '## Terminal goal' in lines else lines.index('# HISTORY — the roadmap in full') + 2
hist = ['Status: %s CURRENT (D11-L: the full pre-split ROADMAP text, verbatim — pulls, task bodies, progress log, decisions D1-D11 with their evidence; ROADMAP.md holds the thesis, TG-DONE table, critical path and measured table; TASKS.md the ledger)' % datetime.date.today(), '',
        '# HISTORY — the roadmap in full', ''] + lines[i_goal:]
if not (len(sys.argv) > 2 and sys.argv[1] == '--from'):
    open('HISTORY.md', 'w').write('\n'.join(hist) + '\n')
print('TASKS.md', len(tasks), 'lines; HISTORY.md', len(hist), 'lines; statuses', dict(cnt))
